default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: 5432
  username: <%= ENV['AMO_DATABASE_USERNAME'] %>
  password: <%= ENV['AMO_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: amo_development

test:
  <<: *default
  database: amo_test

production:
  <<: *default
  database: amo_production
